# Generated by Django 4.2 on 2023-06-01 04:02

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('author', models.CharField(max_length=250)),
                ('url', models.URLField(null=True)),
                ('content', models.TextField()),
                ('public_day', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(default='stories_media/images/default.jpg', upload_to='stories_media/images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stories.category')),
            ],
        ),
    ]
