# Generated by Django 4.2 on 2023-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='static/images'),
        ),
    ]
