# Generated by Django 4.2 on 2023-06-22 09:14

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(default='shop_media/default.png', upload_to='shop_media/category/')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(default='sku', max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('value', models.CharField(blank=True, max_length=150)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SKU', max_length=150)),
                ('sku_code', models.CharField(default='sku', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, unique=True)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(default='shop_media/default.png', upload_to='shop_media/customer/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(default='shop_media/default.png', upload_to='shop_media/category/')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('priceOrg', models.FloatField(null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('viewed', models.IntegerField(default=0)),
                ('quantity_remaining', models.IntegerField(default=0)),
                ('quantity_purchased', models.IntegerField(default=0)),
                ('public_day', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(default='shop_media/default.png', upload_to='shop_media/product/')),
                ('banner', models.ImageField(default='shop_media/default.png', upload_to='shop_media/product/')),
                ('rate', models.FloatField(default=0)),
                ('option', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='option', to='shop.option')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)subcategory', to='shop.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('quantility', models.IntegerField(default=0)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('status', models.IntegerField(choices=[(0, 'failed'), (1, 'success'), (2, 'wait')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
    ]
