# Generated by Django 4.2 on 2023-06-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_purchased',
            field=models.IntegerField(default=0),
        ),
    ]
