# Generated by Django 4.2 on 2023-06-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='sku_code',
            field=models.CharField(default='sku', max_length=150),
        ),
    ]
